name: ecs

on:
  push:

jobs:
  rector:
    runs-on: ubuntu-latest
    name: ECS ${{ matrix.rule }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2

      - name: Install dependencies
        uses: ramsey/composer-install@v1

      - name: ECS without react/promise
        run: vendor/bin/ecs check
